packages:
  - "packages/*"
  - "playgrounds/*"

catalogMode: prefer

catalog:
  "@changesets/changelog-github": ^0.7.0
  "@changesets/cli": ^2.31.0
  typescript: ^6.0.3
  vite: "npm:@voidzero-dev/vite-plus-core@^0.1.24"
  vite-plus: ^0.1.24
  vitest: "npm:@voidzero-dev/vite-plus-test@^0.1.24"

peerDependencyRules:
  allowedVersions:
    vite: "*"
    vitest: "*"
